# Generated by Django 5.2 on 2025-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('current_station_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
